[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["bash build.sh"]

[start]
cmd = "python api_server.py"
